[package]
name = "roam-db-find-referenced-files"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
log = "0.4.28"
org-roam-db = { git = "https://github.com/egregius313/org-roam-db-rs", version = "0.1.0" }
rusqlite = "0.37.0"
